common:
  lang: en # en, ru, <any>(may be ugly)
  mode: training # exam, training
  course_of_study_step: 1 # for ./course-of-study.sh
exam:
  speed:
    outside_the_exercise:
      speech_percents: 100 # 50 <-> 500, TODO: 0(for disable)
      signals_percents: 100
    throughout_the_exercise:
      announcement_number_percents: 200
      delay_between_numbers_ms: 3000
      announcement_enter_answer_percents: 200
training:
  max_count_numbers_per_stage: 3 # 1 <-> 9999...
  check_stage_result_method: yes-no # input, yes-no
  speed:
    outside_the_exercise:
      speech_percents: 500
      signals_percents: 500
    throughout_the_exercise:
      announcement_stage_percents: 500
      signal_start_stage_percents: 500
      announcement_number_percents: 500
      delay_between_numbers_ms: 0 # 0 <-> 9999...
      announcement_stage_result_percents: 500
      announcement_enter_stage_result_percents: 500
