common:
  lang: en # en, ru, TODO:<any> (may be ugly)
  user_name: df09 # 1-6 chars
  analyze_spoilers: no # yes, no
  study_program:
    # допуск к экзамену - сколько раз подряд нужно сдать training
    passes_for_exam: 3 # 1 <-> 9999...
    # пересдача - сколько раз подряд можно провалить экзамен
    fails_for_retake: 3 # 0 <-> 9999...
exam:
  non_exercise:
    speech_spdpct: 500 # 50 <-> 500, 0 (disable)
    signals_spdpct: 500
  during_exercise:
    number_spdpct: 500
    number_delay_ms: 0 # 0 <-> 9999...
    unaryplus_show: yes
    unaryplus_spdpct: 500
    result_entry_spdpct: 500
training:
  numbers_per_stage: 2  # 1 <-> 9999...
  check_result_method: yes_no  # input, yes_no
  non_exercise:
    speech_spdpct: 500
    signals_spdpct: 500
  during_exercise:
    startstage_announce_spdpct: 500
    startstage_signal_spdpct: 500
    continuewith_announce_spdpct: 500
    continuewith_number_spdpct: 500
    number_spdpct: 500
    number_delay_ms: 500
    unaryplus_show: yes
    unaryplus_spdpct: 500
    result_announce_spdpct: 500
    result_number_spdpct: 500
    result_entry_spdpct: 500
    result_wrong_spdpct: 500
