common:
  lang: en # en, ru, [TODO] <any> (may be ugly)
  mode: training # exam, training, [TODO] study_program
  # Course of study program:
  # Step  Mode      Time  Command args
  #  1    training  4:00  run-new cover-units plus x-x
  #  2    exam      4:00  run-new cover-units plus x-x
  #  3    training  4:00  run-new cover-units minus x-x
  #  4    exam      4:00  run-new cover-units minus x-x
  #  5    training  4:00  run-new cover-units plus xx-xx
  #  6    exam      4:00  run-new cover-units plus xx-xx
  #  7    training  4:00  run-new cover-units minus xx-xx
  #  8    exam      4:00  run-new cover-units minus xx-xx
  #  9    training  8:00  run-new cover-units plus-minus-roudtrip xx-xx
  #  10   exam      8:00  run-new cover-units plus-minus-roudtrip xx-xx
  #  11   training  4:00  run-new cover-units plus-minus xx-xx
  #  12   exam      4:00  run-new cover-units plus-minus xx-xx
  study_program: # [TODO]
    student_name: alice
    swith_mode_policy:
      # after X consecutive training sessions without repetitions and in time
      training2exam: 1 # 0 <-> 9999...
      # after X consecutive exams with an incorrect answer
      exam2training: 3 # 0 <-> 9999...
exam:
  speed:
    outside_the_exercise:
      speech_percents: 100 # 50 <-> 500, 0 (disable)
      signals_percents: 100
    throughout_the_exercise:
      announce_number_percents: 200
      delay_between_numbers_ms: 3000 # 0 <-> 9999...
      announce_enter_answer_percents: 200
training:
  max_count_numbers_per_stage: 10 # 1 <-> 9999...
  check_stage_result_method: yes-no # input, yes-no
  speed:
    outside_the_exercise:
      speech_percents: 100
      signals_percents: 100
    throughout_the_exercise:
      announce_stage_percents: 200
      announce_stage_continue_with_text_percents: 200
      announce_stage_continue_with_number_percents: 100
      signal_start_stage_percents: 200
      announce_number_percents: 100
      delay_between_numbers_ms: 3000
      announce_stage_result_text_percents: 200
      announce_stage_result_number_percents: 100
      signal_wrong_stage_result_percents: 100
      announce_enter_stage_result_percents: 100
